######################################################################
# Automatically generated by qmake (3.0) Tue Aug 8 14:19:53 2017
######################################################################

TEMPLATE = app
TARGET = CWK2
INCLUDEPATH += . /opt/local/include

LIBS += -lglut -lGLU
QT += widgets opengl gui

# Input
HEADERS += CWK2Widget.h CWK2Window.h Image.h
SOURCES += Main.cpp \
           CWK2Widget.cpp \
           CWK2Window.cpp \
           Image.cpp 
